version: 0.2

env:
  shell: bash
  variables:
    IMAGE_TAG: '2.14.1'
    IMAGE: 'quay.io/robszumski/log4jpoc'
    NAME: 'log4jpoc-codebuild'
    EDGEBIT_URL: 'https://rob.edgebit.io'
    REPO: 'https://github.com/robszumski/log4jpoc'
  secrets-manager:
    EDGEBIT_API_KEY: rob.edgebit.io/EdgeBitAPIKey
    GH_TOKEN: robszumski/GitHub/AccessToken

phases:
  build:
    commands:
      - FULL_IMAGE="$IMAGE:$IMAGE_TAG"
      # - docker build -t $FULL_IMAGE .
      - docker pull --quiet $FULL_IMAGE
      - docker tag $FULL_IMAGE $IMAGE:$IMAGE_TAG
      - |
        bash .cicd/edgebit.sh \
          --version $IMAGE_TAG \
          --local-image $IMAGE:$IMAGE_TAG \
          --remote-image $FULL_IMAGE \
          --repo $REPO \
          --component-name $NAME \
        || true # this will trap errors
      