version: 0.2

env:
  shell: bash
  variables:
    IMAGE_TAG: '2.14.1'
    IMAGE: 'quay.io/robszumski/log4jpoc'
    NAME: 'log4jpoc'
    EDGEBIT_URL: 'https://rob.edgebit.io'
    GH_REPO: 'https://github.com/robszumski/log4jpoc'
  secrets-manager:
    EDGEBIT_API_KEY: rob.edgebit.io/EdgeBitAPIKey
    GH_TOKEN: robszumski/GitHub/AccessToken

phases:
  install:
    commands:
      # Install ebctl v0.5.1
      - curl -sL $(curl -s https://api.github.com/repos/edgebitio/edgebit-cli/releases/tags/v0.5.1 | jq -r '.assets[] | select(.name|match("^edgebit-cli_Linux_x86_64(.*)tar.gz$")) | .browser_download_url') --output ebctl.tar.gz
      - tar -xvf ebctl.tar.gz
      - chmod +x ebctl
      # Install syft v0.74.1
      - curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b . v0.74.1
  pre_build:
    commands:
      # Get the current commit SHA
      - LATEST_SHA=$(git rev-parse HEAD)
      # Find if the current SHA is associated with a PR
      - |
        GH_PR_NUMBER=$(curl --request GET \
          --silent \
          --header "Authorization: Bearer ${GH_TOKEN}" \
          --header "X-GitHub-Api-Version: 2022-11-28" \
          --url "https://api.github.com/search/issues?q=${LATEST_SHA}" | jq -r .items[0].number)
      - echo $GH_PR_NUMBER
      # Grab the repo API address for use in later API calls
      - |
        GH_API_LOCATION=$(curl --request GET \
          --silent \
          --header "Authorization: Bearer ${GH_TOKEN}" \
          --header "X-GitHub-Api-Version: 2022-11-28" \
          --url "https://api.github.com/search/issues?q=${LATEST_SHA}" | jq -r .items[0].repository_url)
      # If a PR number was found, find the base SHA of it for diff-ing
      - |
          if [[ "$GH_PR_NUMBER" =~ ^[0-9]+$ ]]; then
            BASE_SHA=$(curl --request GET \
              --silent \
              --header "Authorization: Bearer ${GH_TOKEN}" \
              --header "X-GitHub-Api-Version: 2022-11-28" \
              --url "${GH_API_LOCATION}/pulls/${GH_PR_NUMBER}" | jq -r .base.sha)
          else
            BASE_SHA=$LATEST_SHA
          fi
      - echo $BASE_SHA
      - FULL_IMAGE="$IMAGE:$IMAGE_TAG"
  build:
    commands:
      - docker build -t $FULL_IMAGE .
      # Generate SBOM
      - ./syft packages $FULL_IMAGE -o syft > $NAME.syft
      # Upload SBOM for diff-ing and get a PR comment body back
      - |
        ./ebctl upload-sbom-for-ci \
          --component $NAME \
          --tag latest \
          --tag $IMAGE_TAG \
          --repo $GH_REPO \
          --commit $LATEST_SHA \
          --image-tag $FULL_IMAGE \
          --base-commit $BASE_SHA \
          $NAME.syft > ./edgebit-comment-body.json
      - cat ./edgebit-comment-body.json
      # Comment on PR if it exists and skip_comment is false
      - |
          if [[ $(cat ./edgebit-comment-body.json | jq -r .skip_comment) == false ]] && [[ "$GH_PR_NUMBER" =~ ^[0-9]+$ ]]; then
            curl -L -X POST \
              --silent \
              --header "Authorization: Bearer ${GH_TOKEN}" \
              --header "X-GitHub-Api-Version: 2022-11-28" \
              --header "Accept: application/vnd.github+json" \
              -d "{\"body\": \"$(cat ./edgebit-comment-body.json | jq -r .comment_body)\"}" \
              --url "${GH_API_LOCATION}/issues/${GH_PR_NUMBER}/comments"
          fi