version: 0.2

env:
  shell: bash
  variables:
    IMAGE_TAG: '2.14.1'
    IMAGE: 'quay.io/robszumski/log4jpoc'
    NAME: 'log4jpoc-codebuild'
    EDGEBIT_URL: 'https://rob.edgebit.io'
    REPO: 'https://github.com/robszumski/log4jpoc'
  secrets-manager:
    EDGEBIT_API_KEY: rob.edgebit.io/EdgeBitAPIKey
    GH_TOKEN: robszumski/GitHub/AccessToken

phases:
  install:
    commands:
      # Install ebctl v0.5.1
      - curl -sL https://install.edgebit.io/releases/edgebit-cli/latest/edgebit-cli_Linux_x86_64.tar.gz --output ebctl.tar.gz
      - tar -xvf ebctl.tar.gz
      - chmod +x ebctl
      # Install syft v0.74.1
      - curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b . v0.74.1
      # Install gh CLI
      - sudo yum install git -y
      - curl -L https://github.com/cli/cli/releases/download/v2.37.0/gh_2.37.0_linux_amd64.rpm > gh_2.37.0_linux_amd64.rpm
      - rpm -i gh_2.37.0_linux_amd64.rpm
  pre_build:
    commands:
      # Gather GitHub details
      - LATEST_SHA=$(git rev-parse HEAD)
      - GH_DEFAULT_BRANCH=$(gh repo view --json defaultBranchRef $REPO | jq -r .defaultBranchRef.name)
      - echo "$GH_DEFAULT_BRANCH"
      - GH_IS_DEFAULT=$(git merge-base --is-ancestor HEAD origin/$GH_DEFAULT_BRANCH && echo "1" || echo "0")
      - echo "$GH_IS_DEFAULT"
      - GH_PR_NUMBER=$(gh pr list --repo "$REPO" --search "$LATEST_SHA" --json number --jq .[].number)
      - echo "$GH_PR_NUMBER"
      - |
          if [[ "$GH_IS_DEFAULT" = 1 ]]; then
            EDGEBIT_EXTRA_TAG="latest"
          else
            EDGEBIT_EXTRA_TAG="pr-${GH_PR_NUMBER}"
          fi
      - echo "$EDGEBIT_EXTRA_TAG"
      - FULL_IMAGE="$IMAGE:$IMAGE_TAG"
  build:
    commands:
      - docker build -t $FULL_IMAGE .
      # Generate SBOM
      - ./syft packages $FULL_IMAGE -o syft > $NAME.syft
      # Upload SBOM for diff-ing
      - ./ebctl upload-sbom --component $NAME --tag $EDGEBIT_EXTRA_TAG --tag $IMAGE_TAG --repo $REPO --commit $LATEST_SHA --image-tag $FULL_IMAGE $NAME.syft
