version: 0.2

env:
  shell: bash
  variables:
    IMAGE_TAG: '2.14.1'
    IMAGE: 'quay.io/robszumski/log4jpoc'
    NAME: 'log4jpoc-codebuild'
    EDGEBIT_URL: 'https://rob.edgebit.io'
    GH_REPO: 'https://github.com/robszumski/log4jpoc'
  secrets-manager:
    EDGEBIT_API_KEY: rob.edgebit.io/EdgeBitAPIKey

phases:
  install:
    commands:
      # Install ebctl v0.5.1
      - curl -sL $(curl -s https://api.github.com/repos/edgebitio/edgebit-cli/releases/tags/v0.5.1 | jq -r '.assets[] | select(.name|match("^edgebit-cli_Linux_x86_64(.*)tar.gz$")) | .browser_download_url') --output ebctl.tar.gz
      - tar -xvf ebctl.tar.gz
      - chmod +x ebctl
      # Install syft v0.74.1
      - curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b . v0.74.1
  pre_build:
    commands:
      # Get the current commit SHA
      - LATEST_SHA=$(git rev-parse HEAD)
      - FULL_IMAGE="$IMAGE:$IMAGE_TAG"
  build:
    commands:
      - docker build -t $FULL_IMAGE .
      # Generate SBOM
      - ./syft packages $FULL_IMAGE -o syft > $NAME.syft
      # Upload SBOM to component
      - |
        ./ebctl upload-sbom \
          --component $NAME \
          --tag latest \
          --tag $IMAGE_TAG \
          --repo $GH_REPO \
          --commit $LATEST_SHA \
          --image-tag $FULL_IMAGE \
          $NAME.syft